[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/","@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",  "forge-std/=lib/forge-std/src/", "solmate/=lib/solmate/src/"]
solc = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config